FROM node:18
WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend/ ./
COPY prisma/ ./prisma/
RUN npx prisma generate
RUN npx prisma migrate deploy
RUN npm run production
EXPOSE 9000

CMD ["npm", "start"]