name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd c21-44-t-node-react/
          docker compose down
          docker image rmi c21-44-t-node-react-backend:latest
          docker image rmi c21-44-t-node-react-frontend:latest
          docker compose build --no-cache
          docker compose up -d
          EOF
